### PR TITLE
Bind "g" to headers-rerun-search

### PR DESCRIPTION
**Pull request by lbolla**
I think it's very useful to be able to re-run the latest search in the "headers" view, e.g. after having marked messages, etc.
Re-use the original "emacs-mode" binding.

### CODE REVIEW

**Comment by JorisE** [comment]
I think 'g' would be problematic because a vim user expects 'gg' to go to first line. Do you have another idea?

**Comment by lbolla** [comment]
`evil-magit` uses `gr` to "refresh": https://github.com/emacs-evil/evil-magit/blob/master/evil-magit.el#L257
Maybe we can use that too, for consistency?

**Comment by JorisE** [comment]
Yes, I think that would be the most natural combination for evil users.

**Comment by lbolla** [comment]
I've pushed a patch to bind "gr" instead.

**Pull request merged**
