### PR TITLE
More bindings and switch to normal state

### PR DESCRIPTION
**Pull request by Ambrevar**
Evil Collection uses normal state everywhere, so it would be nice if evil-mu4e would follow the same consistency.

This is a work in progress, some bindings from Emacs state need to be added back.

I've removed the dash dependency as it doesn't seem to be used anywhere.
I've also fixed some typos and style.

Let me know what you think, I'll update this PR soon with more complete bindings.

### CODE REVIEW

**Comment by Ambrevar** [comment]
I've taken a shot at adding (almost) all default bindings back.
This should be ready for merging.

Let me know what you think.

@jojojames?  @noctuid?

**Comment by noctuid** [comment]
Are some of the capital letter bindings made for consistency with mu4e's bindings? It seems like several of them could be lowercase (e.g. I use `c` instead of `C` for composition).

**Comment by nighthawk9** [comment]
noctuid, I believe it may be to remain consistent with the other bindings related to Forwarding and Replying. Personally, continuing with the capitalization for those message operations seems fair. I would be very happy with the new bindings suggested in the PR. Hopefully, JorisE will chime in.

**Comment by JorisE** [comment]
Thanks a lot @Ambrevar! This solves a lot of todo's on my list ;)
The capital letters were probably introduced for consistency. I used mu4e before I used the evelified version.

**Comment by Ambrevar** [comment]
The main issue now is that it fails to load when I try to set some keys, such as
```
(,evil-mu4e-state mu4e-compose-mode-map "gg" mu4e-compose-goto-top)
```
Any clue?

**Comment by Ambrevar** [comment]
Regarding the capitals, I think `c` is unused so we could bind it to `mu4e-compose-new` just like `C`.  On the other hand, it could be distrubingly annoying if `c` were an unintended key press.

As for the others:
- `R` is for `reply`, and `r` is for refile.  I personally never refile, so I use `R` more.  But for someone who refiles, the "refile" action might occur more than the reply action, so I think it makes sense to keep it unshifted.
- `F` is for forwarding, `f` is for `evil-find-char`.  I think `evil-find-char` is important so we should leave it that way.  In the same vein, should we keep `F` bound to `evil-find-char-backward` and bind `mu4e-compose-forward` to something else?

**Comment by Ambrevar** [comment]
I think `e` is too important and should not be bound to "save attachments".  I suggest `za` instead.

**Comment by noctuid** [comment]
I think `c` for compose makes sense. Other keys would also be annoying to accidentally press.

I don't think `evil-find-char` is useful in headers mode, is it? Also, `evil-find-char-backward` / `F` is useful in view mode, so I'd think `f` for forwarding in headers mode and something else for view mode would make sense.

Couldn't `za` eventually be used to toggle hiding/showing old `>` text? Maybe something like `gs`?

As for other capital letters, I was also thinking about `N` and `H` in main mode and `E` in headers mode.

I do think it would be nice if the keybindings for reply, compose, forward, etc. were consistent. They can't all be on lowercase keys in both headers and view mode. I personally like the idea of providing better keys for some where possible. It may make sense to allow for a customizable "local leader" here (and in evil-collection for situations like this). For example, I personally have `c` bound to compose but don't use `f` for forwarding in view mode. I do have `f` (and `c`, `r`, etc.) all bound under a prefix for both headers and view mode though.

**Comment by Ambrevar** [comment]
You are right, `evil-find-char` is not so useful in headers mode.
That said, it is much more useful in view mode, so it's hard to bind a
pan-mode function to `f` while keeping consistency.

What about `c` for "compose" and `C` for "forward"?
Or `cc` for "compose" and "cf" for forward?
The latter would make it possible to bind `ce` for "edit" and `cr` for "reply".

Regarding attachments, what about these:

- `p` for "save" and `P` for "save-multi".  Originally for pasting, it
can be thought as "inserting the attachment into your filesystem".  A
bit convoluted, I know...

- `ya` and `yA`, same, for "yank attachment".

Toggle quoting: yes, `za` is a good idea.

Regarding other letters: I don't see a problem with binding `N` and
`H` in the main mode.  What do you mean?

**Comment by noctuid** [comment]
I like the idea of using `c` as a prefix. Maybe `C` and `c` for compose in main mode, and `c` as a prefix everywhere else.

I actually like the `p` idea.

I don't think `ya` should be bound over. I've used outer text objects for yanking email text before.

> Regarding other letters: I don't see a problem with binding `N` and `H` in the main mode. What do you mean?

I just meant that they could be lowercase as well.

**Comment by Ambrevar** [comment]
`ya`: Wow, I must have been tired, I completely forgot `a` was an adverb.

`N` and `H`: well, it's true that there is no much use in moving around the main buffer, but `h` and `n` are so important that could be disturbing...

**Pull request merged**
